/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.wesleyegberto.kafkaavro.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PersonMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1085240378946845251L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PersonMessage\",\"namespace\":\"com.github.wesleyegberto.kafkaavro.models\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Full name\"},{\"name\":\"birthDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Birth date\",\"default\":\"\"},{\"name\":\"address\",\"type\":{\"type\":\"record\",\"name\":\"AddressMessage\",\"fields\":[{\"name\":\"street\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"postalCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"active\",\"type\":\"boolean\",\"default\":true}]}},{\"name\":\"emails\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PersonMessage> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PersonMessage> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PersonMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PersonMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PersonMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PersonMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PersonMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PersonMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PersonMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  /** Full name */
  private java.lang.String name;
  /** Birth date */
  private java.lang.String birthDate;
  private com.github.wesleyegberto.kafkaavro.models.AddressMessage address;
  private java.util.List<java.lang.String> emails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PersonMessage() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name Full name
   * @param birthDate Birth date
   * @param address The new value for address
   * @param emails The new value for emails
   */
  public PersonMessage(java.lang.Long id, java.lang.String name, java.lang.String birthDate, com.github.wesleyegberto.kafkaavro.models.AddressMessage address, java.util.List<java.lang.String> emails) {
    this.id = id;
    this.name = name;
    this.birthDate = birthDate;
    this.address = address;
    this.emails = emails;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return birthDate;
    case 3: return address;
    case 4: return emails;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: birthDate = value$ != null ? value$.toString() : null; break;
    case 3: address = (com.github.wesleyegberto.kafkaavro.models.AddressMessage)value$; break;
    case 4: emails = (java.util.List<java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Full name
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Full name
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'birthDate' field.
   * @return Birth date
   */
  public java.lang.String getBirthDate() {
    return birthDate;
  }


  /**
   * Sets the value of the 'birthDate' field.
   * Birth date
   * @param value the value to set.
   */
  public void setBirthDate(java.lang.String value) {
    this.birthDate = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public com.github.wesleyegberto.kafkaavro.models.AddressMessage getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(com.github.wesleyegberto.kafkaavro.models.AddressMessage value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'emails' field.
   * @return The value of the 'emails' field.
   */
  public java.util.List<java.lang.String> getEmails() {
    return emails;
  }


  /**
   * Sets the value of the 'emails' field.
   * @param value the value to set.
   */
  public void setEmails(java.util.List<java.lang.String> value) {
    this.emails = value;
  }

  /**
   * Creates a new PersonMessage RecordBuilder.
   * @return A new PersonMessage RecordBuilder
   */
  public static com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder newBuilder() {
    return new com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder();
  }

  /**
   * Creates a new PersonMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PersonMessage RecordBuilder
   */
  public static com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder newBuilder(com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder other) {
    if (other == null) {
      return new com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder();
    } else {
      return new com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder(other);
    }
  }

  /**
   * Creates a new PersonMessage RecordBuilder by copying an existing PersonMessage instance.
   * @param other The existing instance to copy.
   * @return A new PersonMessage RecordBuilder
   */
  public static com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder newBuilder(com.github.wesleyegberto.kafkaavro.models.PersonMessage other) {
    if (other == null) {
      return new com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder();
    } else {
      return new com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for PersonMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PersonMessage>
    implements org.apache.avro.data.RecordBuilder<PersonMessage> {

    private long id;
    /** Full name */
    private java.lang.String name;
    /** Birth date */
    private java.lang.String birthDate;
    private com.github.wesleyegberto.kafkaavro.models.AddressMessage address;
    private com.github.wesleyegberto.kafkaavro.models.AddressMessage.Builder addressBuilder;
    private java.util.List<java.lang.String> emails;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.birthDate)) {
        this.birthDate = data().deepCopy(fields()[2].schema(), other.birthDate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.address)) {
        this.address = data().deepCopy(fields()[3].schema(), other.address);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasAddressBuilder()) {
        this.addressBuilder = com.github.wesleyegberto.kafkaavro.models.AddressMessage.newBuilder(other.getAddressBuilder());
      }
      if (isValidValue(fields()[4], other.emails)) {
        this.emails = data().deepCopy(fields()[4].schema(), other.emails);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing PersonMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.wesleyegberto.kafkaavro.models.PersonMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.birthDate)) {
        this.birthDate = data().deepCopy(fields()[2].schema(), other.birthDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.address)) {
        this.address = data().deepCopy(fields()[3].schema(), other.address);
        fieldSetFlags()[3] = true;
      }
      this.addressBuilder = null;
      if (isValidValue(fields()[4], other.emails)) {
        this.emails = data().deepCopy(fields()[4].schema(), other.emails);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Full name
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Full name
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Full name
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * Full name
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'birthDate' field.
      * Birth date
      * @return The value.
      */
    public java.lang.String getBirthDate() {
      return birthDate;
    }


    /**
      * Sets the value of the 'birthDate' field.
      * Birth date
      * @param value The value of 'birthDate'.
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder setBirthDate(java.lang.String value) {
      validate(fields()[2], value);
      this.birthDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'birthDate' field has been set.
      * Birth date
      * @return True if the 'birthDate' field has been set, false otherwise.
      */
    public boolean hasBirthDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'birthDate' field.
      * Birth date
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder clearBirthDate() {
      birthDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public com.github.wesleyegberto.kafkaavro.models.AddressMessage getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder setAddress(com.github.wesleyegberto.kafkaavro.models.AddressMessage value) {
      validate(fields()[3], value);
      this.addressBuilder = null;
      this.address = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.github.wesleyegberto.kafkaavro.models.AddressMessage.Builder getAddressBuilder() {
      if (addressBuilder == null) {
        if (hasAddress()) {
          setAddressBuilder(com.github.wesleyegberto.kafkaavro.models.AddressMessage.newBuilder(address));
        } else {
          setAddressBuilder(com.github.wesleyegberto.kafkaavro.models.AddressMessage.newBuilder());
        }
      }
      return addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'address' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder setAddressBuilder(com.github.wesleyegberto.kafkaavro.models.AddressMessage.Builder value) {
      clearAddress();
      addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'address' field has an active Builder instance
     * @return True if the 'address' field has an active Builder instance
     */
    public boolean hasAddressBuilder() {
      return addressBuilder != null;
    }

    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder clearAddress() {
      address = null;
      addressBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'emails' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getEmails() {
      return emails;
    }


    /**
      * Sets the value of the 'emails' field.
      * @param value The value of 'emails'.
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder setEmails(java.util.List<java.lang.String> value) {
      validate(fields()[4], value);
      this.emails = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'emails' field has been set.
      * @return True if the 'emails' field has been set, false otherwise.
      */
    public boolean hasEmails() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'emails' field.
      * @return This builder.
      */
    public com.github.wesleyegberto.kafkaavro.models.PersonMessage.Builder clearEmails() {
      emails = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PersonMessage build() {
      try {
        PersonMessage record = new PersonMessage();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.birthDate = fieldSetFlags()[2] ? this.birthDate : (java.lang.String) defaultValue(fields()[2]);
        if (addressBuilder != null) {
          try {
            record.address = this.addressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("address"));
            throw e;
          }
        } else {
          record.address = fieldSetFlags()[3] ? this.address : (com.github.wesleyegberto.kafkaavro.models.AddressMessage) defaultValue(fields()[3]);
        }
        record.emails = fieldSetFlags()[4] ? this.emails : (java.util.List<java.lang.String>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PersonMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<PersonMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PersonMessage>
    READER$ = (org.apache.avro.io.DatumReader<PersonMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.name);

    out.writeString(this.birthDate);

    this.address.customEncode(out);

    long size0 = this.emails.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.emails) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.name = in.readString();

      this.birthDate = in.readString();

      if (this.address == null) {
        this.address = new com.github.wesleyegberto.kafkaavro.models.AddressMessage();
      }
      this.address.customDecode(in);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.emails;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("emails").schema());
        this.emails = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.name = in.readString();
          break;

        case 2:
          this.birthDate = in.readString();
          break;

        case 3:
          if (this.address == null) {
            this.address = new com.github.wesleyegberto.kafkaavro.models.AddressMessage();
          }
          this.address.customDecode(in);
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.emails;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("emails").schema());
            this.emails = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










