spring.application.name=spring-boot-ai

spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql
spring.sql.init.continue-on-error=false
spring.sql.init.encoding=UTF-8

spring.datasource.url=jdbc:postgresql://localhost:5433/postgresml
spring.datasource.username=springai
spring.datasource.password=unhackable

# allow to reference more than one model
spring.ai.model.chat=ollama
# allow to define which embedding to use
spring.ai.model.embedding=ollama

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
# Ollama model to be used (must be installed with `ollama pull`)
spring.ai.ollama.chat.options.model=gemma3:12b
spring.ai.ollama.chat.options.temperature=0.2
# Claude
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}

# database schema to store chat memory
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
# vector store configuration
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1024
# configure the type of vector to be used for embedding
spring.ai.postgresml.embedding.options.vector-type=pg-vector
spring.ai.postgresml.embedding.create-extension=true
